<?php

test('admin promotions page renders the front-end promo workspace', function () {
    $this->actingAs(adminUser())
        ->get(route('admin.promotions'))
        ->assertSuccessful()
        ->assertSee('Promotions')
        ->assertSee('Create discounts to delight customers.')
        ->assertSee('Search orders, products, customers...')
        ->assertSee('New Promo Code')
        ->assertSee('Promo code')
        ->assertSee('Discount type')
        ->assertSee('Discount value')
        ->assertSee('Start date')
        ->assertSee('Expiry date')
        ->assertSee('Active promo')
        ->assertSee('Image ad')
        ->assertSee('Promo Codes')
        ->assertSee('SWEET20')
        ->assertSee('DONUTLOVE')
        ->assertSee('data-admin-promotions', false)
        ->assertSee('data-promotion-global-search', false)
        ->assertSee('role="switch"', false)
        ->assertSee('aria-label="Manage SWEET20"', false)
        ->assertSee('aria-label="Email SWEET20"', false)
        ->assertSee('Customer email')
        ->assertSee('Send promo code')
        ->assertSee('href="'.route('admin.promotions').'" aria-current="page"', false)
        ->assertDontSee('aria-label="Edit SWEET20"', false)
        ->assertDontSee('Active Promos')
        ->assertDontSee('Image Ads')
        ->assertDontSee('Scheduled Drafts')
        ->assertDontSee('Email Ready')
        ->assertDontSee('Send email draft');
});
