<?php

test('admin analytics page renders filters summary cards and paginated reports', function () {
    $this->get(route('admin.analytics'))
        ->assertSuccessful()
        ->assertSee('Analytics')
        ->assertSee('Date range')
        ->assertSee('Today')
        ->assertSee('This Week')
        ->assertSee('This Month')
        ->assertSee('This Year')
        ->assertDontSee('Custom Date Range')
        ->assertSee('Total Revenue')
        ->assertSee('Total Orders')
        ->assertSee('Total Customers')
        ->assertSee('Best-Selling Product')
        ->assertSee('Pastel Donut Box')
        ->assertSee('Sales report')
        ->assertSee('Customer')
        ->assertSee('Product ordered')
        ->assertSee('Quantity')
        ->assertDontSee('Status')
        ->assertSee('Product performance')
        ->assertSee('Top-selling desserts and stock turnover.')
        ->assertSee('Rows')
        ->assertSee('6 rows')
        ->assertSee('9 rows')
        ->assertSee('12 rows')
        ->assertSee('Showing 1-6 of 9 sales')
        ->assertSee('Showing 1-6 of 9 desserts')
        ->assertSee('data-admin-analytics', false)
        ->assertSee('data-analytics-table', false)
        ->assertSee('data-analytics-row', false)
        ->assertSee('data-analytics-page-size', false)
        ->assertSee('data-analytics-page-buttons', false)
        ->assertSee('href="'.route('admin.analytics').'" aria-current="page"', false);
});
